name: format + publishable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format_dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.12.0 # Can be updated once https://github.com/subosito/flutter-action/issues/277 is resolved
        with:
          channel: "stable"
      - name: Format
        run: |
          flutter format --set-exit-if-changed .

  format_kotlin:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
      - uses: actions/checkout@v4

      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v1"

  format_swift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  publishable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.12.0 # Can be updated once https://github.com/subosito/flutter-action/issues/277 is resolved
        with:
          channel: "stable"

      - name: publish checks
        run: |
          flutter pub get
          flutter pub publish -n
          flutter pub global activate tuneup
          flutter pub global run tuneup check
